### PR TITLE
feat(ZMSP-19): Add Multi Select for multiple service types

### PR DESCRIPTION
**Pull request by vogelino**
This PR adds a multi select so that many services can be selected for a process

### CODE REVIEW

**Review by ff6347 — APPROVED** [review]
Awesome. Your are code generating machine. Only thing is the PR against main instead of staging. But this does not affect the DB code. Still would be nice to run against staging first

**Comment by vogelino** [comment]
> Awesome. Your are code generating machine. Only thing is the PR against main instead of staging. But this does not affect the DB code. Still would be nice to run against staging first

Hahaha! In the zone RN!

on-fire-gif-by-nrk-p3

I did change the base branch! Thx!

**Pull request merged**
