### PR TITLE
feat(ZMSP-20, ZMSP-25, ZMSP-23, ZMSP-21, ZMSP-24, ZMSP-27, ZMSP-28)

### PR DESCRIPTION
**Pull request by vogelino**
This PR resolves all the following tickets:
ZMSP-20, ZMSP-25, ZMSP-23, ZMSP-21, ZMSP-24, ZMSP-27, ZMSP-28

### CODE REVIEW

**Comment by ff6347** [comment]
Draft or review? I got a mail but it looks like you are still in progress?

**Comment by vogelino** [comment]
Draft! Unfortunately there is no way to open a PR directly as a draft. If you open it and see it as a draft, it means I t is a draft and just opened the PR to see if all checks passed or to trigger a deploy. :)

**Comment by ff6347** [comment]
works with the github cli

```shell
gh pr create --base staging --fill --draft
```

**Pull request merged**
